name: Check Secrets

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-secrets:
    uses: contratadome/sre-iac/.github/workflows/shared_check_secrets.yml@main
    secrets: inherit
